---
title: "THE NAMIBIAN SHELLFISH SANITATION PROGRAMME (NSSP) REVIEW REPORT FOR 2024/25"
output: word_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r message=FALSE, echo=FALSE}
# read in the raw data
x <- read_excel("Phytoplankton Total Cell_L_2018_2024.xlsx")
```


```{r message=FALSE, echo=FALSE}
# make a new table format to use for the figures
z <- x |>
  distinct() |> # remove duplicates
  filter(!is.na(`Cells/L`)) |> # remove NA cell/l rows
  select(-`SumOfTransect Count`, 
         -Groups, 
         -`Toxin producing species`,
         -`Microscope fields`) |> # remove columns that we won't use
  pivot_wider(names_from = Specie, # columns that contains the names of the new columns
              values_from = `Cells/L`, # column that contains the values for the new columns
              values_fn = max, 
              values_fill = 0) |>
  mutate(`Date Collected` = as.Date(`Date Collected`), # change the date-time column to only date
         year = format(`Date Collected`, format="%Y"), # create a year column
         month = format(`Date Collected`, format="%m"), # create a month column
         .before = Station) |> # specify the location of the new columns
  arrange(`Date Collected`) # order the table by date
```


# BIOTOXINS AND HABs PHYTOPLANKTON

## AST and *Pseudo-nitzschia sp.*

```{r message=FALSE, echo=FALSE}
# find the site-specific annual monthly mean for each of the pseudo-nitzschia groups counted
pn_monthly_mean <- z |>
  select(year, month, Station, `Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`) |>
  pivot_longer(cols = c(`Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`),
               names_to = "Species",
               values_to = "cells") |>
  group_by(Station, year, month) |>
  summarise("Cells/L" = mean(cells),
            sd = sd(cells, na.rm = TRUE),  # Standard deviation
            n = n(),                                        # Number of observations
            se = sd / sqrt(n),                              # Standard error
            .groups = "drop")
```


### Aquapark 1 (PA WB1) for oysters

```{r message=FALSE, echo=FALSE, fig.cap="Pseudo-nitzschia sp. Average cells/L/month in Aquapark 1 for 2018-2024", fig.width=8}
filter(pn_monthly_mean, Station == "Aquapark 1") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1)) 
  #ylim(0, 150000)
```

### Aquapark 4 (PA WB4) for oysters

```{r message=FALSE, echo=FALSE, fig.cap="Pseudo-nitzschia sp. Average cells/L/month in Aquapark 4 (pond 1) for 2018-2024", fig.width=8}
filter(pn_monthly_mean, Station == "Aquapark 4") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```


```{r message=FALSE, echo=FALSE, fig.cap="Pseudo-nitzschia sp. Average cells/L/month in Aquapark 4 (pond 2) for 2018-2024", fig.width=8}
filter(pn_monthly_mean, Station == "Nam Oysters SALT PANS") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```


### Lüderitz second lagoon (PA L2) for oysters

```{r echo=FALSE, message=FALSE}
# find the annual monthly mean for each of the pseudo-nitzschia groups counted at 3 combined Luderitz sites
lud_pn <- filter(z, Station %in% c("Luderitz Mariculture", 
                                   "NamOyster CC Lüderitz", 
                                   "Tetelestai Mariculture Lüderitz")) |>
  select(year, month, `Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`) |>
  pivot_longer(cols = c(`Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`),
               names_to = "Species",
               values_to = "cells") |>
  group_by(year, month) |>
  summarise("Cells/L" = mean(cells))
```

```{r message=FALSE, echo=FALSE, fig.cap="Pseudo-nitzschia sp. Average cells/L/month in Luderitz for 2018-2024", fig.width=8}
 ggplot(data = lud_pn, aes(x = month, y = `Cells/L`, fill = year))  +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```

### Lüderitz (PA L1) for abalone

```{r message=FALSE, echo=FALSE, fig.cap="Pseudo-nitzschia spp. cells-L (>0) – causative species for lipophillics at Luderitz abalone sites", fig.width=8}
filter(z, Station %in% c("Hangana Abalone")) |>
  select(`Date Collected`, year, month, `Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`) |>
  pivot_longer(cols = c(`Pseudo-nitzschia sp.`, `Pseudo-nitzschia delicatissima gr.`, `Pseudo-nitzschia seriata gr.`),
               names_to = "Species",
               values_to = "cells") |>
  filter(cells > 0) |>
  ggplot(aes(x = `Date Collected`, y = cells)) +
  geom_point() +
  theme_classic() +
  labs(x = "Date", y = "Cells/L")
```

## Lipophilic toxins (or DST) and *Dinophysis* spp

```{r message=FALSE, echo=FALSE}
# find the site-specific annual monthly mean for each of the dinophysis groups counted
dn_monthly_mean <- z |>
  select(year, month, Station, `Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`) |>
  pivot_longer(cols = c(`Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`),
               names_to = "Species",
               values_to = "cells") |>
  group_by(Station, year, month) |>
  summarise("Cells/L" = mean(cells))
```

### Aquapark 1 (PA WB1) for oysters

```{r message=FALSE, echo=FALSE, fig.cap="Dinophysis sp. Average cells/L/month in Aquapark 1 for 2018-2024", fig.width=8}
filter(dn_monthly_mean, Station == "Aquapark 1") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1)) 
```

### Aquapark 4 (PA WB4) for oysters

```{r message=FALSE, echo=FALSE, fig.cap="Dinophysis sp. Average cells/L/month in Aquapark 4 (pond 1) for 2018-2024", fig.width=8}
filter(dn_monthly_mean, Station == "Aquapark 4") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1)) 
```

```{r message=FALSE, echo=FALSE, fig.cap="Mean Dinophysis spp cells/L in Aquapark 4 (pond 2) for 2018-2024", fig.width=8}
filter(dn_monthly_mean, Station == "Nam Oysters SALT PANS") |>
  ggplot(aes(x = month, y = `Cells/L`, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1)) 
```


### Lüderitz second lagoon (PA L2) for oysters

```{r echo=FALSE, message=FALSE}
# find the annual monthly mean for each of the dinophysis groups counted at 3 combined Luderitz sites
lud_dn <- filter(z, Station %in% c("Luderitz Mariculture", 
                                   "NamOyster CC Lüderitz", 
                                   "Tetelestai Mariculture Lüderitz")) |>
  select(year, month, `Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`) |>
  pivot_longer(cols = c(`Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`),
               names_to = "Species",
               values_to = "cells") |>
  group_by(year, month) |>
  summarise("Cells/L" = mean(cells))
```


```{r message=FALSE, echo=FALSE, fig.cap="Dinophysis sp. Average cells/L/month in Luderitz for 2018-2024", fig.width=8}
 ggplot(data = lud_dn, aes(x = month, y = `Cells/L`, fill = year))  +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0, 0)) + 
  scale_x_discrete(labels = function(x) month.abb[as.numeric(x)]) +
  labs(x = "Month", y = "Cells/L", fill = "Year") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal", legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```



```{r message=FALSE, echo=FALSE, fig.cap="Dinophysis spp. cells-L – causative species for lipophillics at Luderitz oyster sites", fig.width=8}
filter(z, Station %in% c("Luderitz Mariculture", 
                         "NamOyster CC Lüderitz", 
                         "Tetelestai Mariculture Lüderitz")) |>
  select(`Date Collected`, year, month, `Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`) |>
  pivot_longer(cols = c(`Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`),
               names_to = "Species",
               values_to = "cells") |>
  filter(cells > 0) |>
  ggplot(aes(x = `Date Collected`, y = cells)) +
  geom_point() +
  theme_classic() +
  labs(x = "Date", y = "Cells/L")
```

###	Lüderitz (PA L1) for abalone 

```{r message=FALSE, echo=FALSE, fig.cap="Dinophysis spp. cells-L (>0) – causative species for lipophillics at Luderitz abalone sites", fig.width=8}
filter(z, Station %in% c("Hangana Abalone")) |>
  select(`Date Collected`, year, month, `Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`) |>
  pivot_longer(cols = c(`Dinophysis sp.`, `Dinophysis acuminata`, `Dinophysis fortii`, `Dinophysis accuta`),
               names_to = "Species",
               values_to = "cells") |>
  filter(cells > 0) |>
  ggplot(aes(x = `Date Collected`, y = cells)) +
  geom_point() +
  theme_classic() +
  labs(x = "Date", y = "Cells/L")
```
