---
output:
  officedown::rdocx_document:
    reference_num: false
params:
  station: "Fermar Seafoods CC (109)"
---

```{r echo=FALSE}
# officeverse book link: https://ardata-fr.github.io/officeverse/index.html
```


```{r message=FALSE, echo=FALSE, warning= FALSE}
library(readr)
library(readxl)
library(ggplot2)
library(dplyr)
library(kableExtra)
library(officer)
```

```{r echo=FALSE}
ft_text<-fp_text(color="black", bold=T, font.size=15, font.family="Calibri (Body)")
fp_center<-fp_par(line_spacing = 1.5, text.align="center")
fpar(ftext("REPUBLIC OF NAMIBIA", ft_text), fp_p=fp_center)
fpar(ftext("MINISTRY OF FISHERIES AND MARINE RESOURCES", ft_text), fp_p=fp_center)
```

***

```{r echo=FALSE}
ft_text<-fp_text(color="black", bold=T, font.size=8, font.family="Calibri (Body)")
fp_center<-fp_par(line_spacing = 1.5, text.align="center")
fpar("Directorate of Aquaculture", run_linebreak(), "Enquiries: H. Skrypzeck", run_linebreak(), "Tel: (+264 64) 4101000", run_linebreak()," Fax: (+264 64) 404385",
     run_linebreak(), "P O Box 912", run_linebreak(), "Swakopmund", run_linebreak(), "Namibia")
```


```{r echo=FALSE}
ft_text<-fp_text(color="blue", bold=T, font.size=18, font.family="Calibri (Body)")
fp_center<-fp_par(line_spacing = 1.5, text.align="center", border = fp_border(color = "blue", style = "dotDotDash", width = 3))
fpar(ftext("Namibian Shellfish Sanitation and Biotoxin Monitoring Program", ft_text), fp_p=fp_center)
fpar(ftext(params$station, ft_text), fp_p=fp_center)
```


```{r echo=FALSE}
ft_text<-fp_text(color="blue", bold=T, font.size=18, font.family="Calibri (Body)")
fp_center<-fp_par(line_spacing = 1.5, text.align="center", border = fp_border(color = "blue", width = 3))
fpar(ftext("Oxygen Report", ft_text), fp_p=fp_center)
```

***

```{r echo=FALSE, message=FALSE}
plot_data <- read_excel("Qry_Dissolved O2.xlsx") |>
  mutate(do_mg_l = DissolvedO2/0.7) |>
  group_by(`Sampling Date`, Station, Depth, `Depth (w)`) |>
  summarise(do_mg_l = mean(do_mg_l)) |>
  filter(Station == params$station) |>
  rename("Depth (m)" = "Depth",
         "Dissolved O2" = "do_mg_l")
```


```{r echo=FALSE}
kable(plot_data)
```




```{r echo=FALSE, message=FALSE, fig.width=5, fig.height=3}
ggplot(plot_data, aes(x = `Dissolved O2`, y = `Depth (m)`)) +
  geom_point(color = "blue", size = 3) +
  geom_path(color = "red", linewidth = 0.7) +  # Connect points
  labs(title = "Dissolved O2 Profile by Depth",
       x = "Dissolved Oxygen mg/l",
       y = "Depth") +
  scale_y_reverse(breaks = seq(0, max(plot_data$`Depth (m)`), by = 1)) +# Makes depth increase downward
  scale_x_continuous(limits = c(floor(min(plot_data$`Dissolved O2`)), ceiling(max(plot_data$`Dissolved O2`))), 
                     breaks = seq(floor(min(plot_data$`Dissolved O2`)), ceiling(max(plot_data$`Dissolved O2`)), by = 0.5), 
                     position = "top") + # (position = "top") change of y axis to top
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

