---
title: "Maps"
author: "Johnathan Evanilla"
date: "10/28/2024"
output:
  github_document:
  pdf_document:
---


```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(sf)
  library(rnaturalearth)
  library(leaflet)
})
```

```{r}
source("stations.R")
```


# Load map data from `rnaturalearth`

```{r}
africa <- ne_countries(scale = "large", returnclass = "sf", continent = "Africa") |>
  st_geometry() 

nam <- ne_countries(scale = "large", returnclass = "sf", country = "Namibia") |>
  st_geometry()

coast = ne_coastline(scale = "large", returnclass = 'sf') |>
  st_geometry() 
```

Get the table of station location information

```{r}
s <- get_stations()
```



# base r way


```{r}
plot(nam, col="tan")
```



# leaflet maps


```{r}
leaflet(data=s) |> 
  addTiles() |>
  addCircleMarkers(~lon, ~lat, popup=~htmltools::htmlEscape(station))
```



# ggplot maps


## Namibia


```{r}
bb <- sf::st_bbox(c(xmin = 10, ymin = -30, xmax = 25, ymax = -15), crs = 4326) |>
  sf::st_as_sfc()
```


```{r}
s <- st_as_sf(s, coords=c("lon", "lat"), crs=4326)
```



```{r}
ggplot(data = nam) +
  geom_sf(fill = "antiquewhite") +
  theme_bw()
```

## Walvis Bay stations


```{r}
s_wb <- s[1:4,] |>
  sf::st_as_sf(coords=c("lon", "lat"), crs=4326)
```

```{r}
bb <- st_bbox(c(xmin = 14.4, ymin = -22.9, xmax = 14.5, ymax = -23.0)) |>
  st_as_sfc()
```

```{r}
wb <- st_crop(nam, bb)
```


```{r warning=FALSE}
ggplot(data = wb) +
  geom_sf(fill = "antiquewhite") +
  geom_sf(data = s_wb) +
  geom_sf_text(data=s_wb, aes(label=station_id), nudge_y=0.005) +
  theme_bw()
```


## Luderitz stations


```{r}
s_lz <- s[5:8,]
```

```{r}
bb_lz <- st_bbox(c(xmin = 15.1, ymin = -26.7, xmax = 15.2, ymax = -26.6)) |>
  st_as_sfc()
```


```{r}
lz <- st_crop(nam, bb_lz)
```


```{r warning=FALSE}
ggplot(data = lz) +
  geom_sf(fill = "antiquewhite") +
  geom_sf(data = s_lz) +
  geom_sf_text(data=s_lz, aes(label=station_id), nudge_y=0.005) +
  theme_bw()
```

