---
title: "Data Visualisation"
author: "Johnathan Evanilla"
date: "10/28/2024"
---

```{r}
#| include=FALSE
library(dplyr)
library(ggplot2)
library(readxl)
```

```{r}
file <- file.path("~/Documents/Bigelow/data/Qry_Phytoplankton Total Cell_L DATA.XLSX")
```


```{r}
x <- read_excel(file) |>
  mutate(month = format(`Date Collected`, format="%m"),
         week = format(`Date Collected`, format="%m"))
```


```{r}
summary(x)
```

```{r}
glimpse(x)
```


```{r}
count(x, Station)
```

```{r}
count(x, Depth)
```

```{r}
hist(x$`SumOfTransect Count`)
```


```{r}
sp <- count(x, Specie)

sp
```

```{r}
View(sp)
```


# Alexandrium 

```{r}
al <- filter(x, Specie == "Alexandrium sp.")
```


```{r}
al
```

```{r}
count(al, Station)
```

# binwidth, log scale

```{r}
hist(al$`Cells/L`)
```


```{r}
plot(`Cells/L`~month, data=al)
```

# Dinophysis

```{r}
dn <- filter(x, Specie == "Dinophysis acuminata")
```

```{r}
count(dn, Station)
```

```{r}
hist(dn$`Cells/L`)
```

```{r}
hist(log10(dn$`Cells/L`))
```

```{r}
plot(`Cells/L`~month, data=dn)
```

